---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejsapp
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      imagePullSecrets:
      - name: regcred1
      containers:
      - name: nodejsapp
        image: nodejsapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: default
spec:
  selector:
    app: nodejsapp
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred1
data:
  .dockerconfigjson: base64-encoded-contents-of-.docker/config.json-file
type: kubernetes.io/dockerconfigjson
