---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejsapp
  namespace: default
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: 10.210.0.83:8085/nodejsapp:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred2
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: default
spec:
  selector:
    app: nodejsapp
  type: NodePort
  ports:
  - name: http
    targetPort: 3000
    port: 80
